"""Integration tests for parsers_hybrid/_media_extract.py on real fixture bytes.

The unit tests in test_media_extract.py cover synthetic/hand-rolled byte
sequences. These tests load real JPEG/MP4 fixture files from
tests/parsers/fixtures/media/ and run extract_gps_from_media() against
them, providing a regression guard against accidental changes to the
binary parser contracts.

Fixtures:
- exif_gps_kiev.jpg — minimal JPEG with EXIF GPS at lat=50.4501, lon=30.5234
  (WGS84, central Kiev).
- qt_location_kiev.mp4 — minimal MP4 with QuickTime ISO 6709 location atom
  at lat=50.4501, lon=30.5234.

These files were generated by build_media_fixtures.py (one-shot script,
not committed) during PR #109 work; the bytes are checked into the repo
so the tests are stable across environments.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from parser_universal.media.exif import (
    extract_gps_from_jpeg,
    extract_gps_from_media,
    extract_gps_from_quicktime,
)

FIXTURE_DIR = Path(__file__).parent.parent / "data" / "media"

JPEG_PATH = FIXTURE_DIR / "exif_gps_kiev.jpg"
MP4_PATH = FIXTURE_DIR / "qt_location_kiev.mp4"

pytestmark = pytest.mark.skipif(
    not JPEG_PATH.exists() or not MP4_PATH.exists(),
    reason="media fixtures not present",
)


def test_exif_jpeg_fixture_extracts_kiev_coords():
    """JPEG with EXIF GPS at +50.4501+030.5234 → (50.4501, 30.5234)."""
    data = JPEG_PATH.read_bytes()
    result = extract_gps_from_jpeg(data)
    assert result is not None
    assert abs(result["lat"] - 50.4501) < 1e-3
    assert abs(result["lon"] - 30.5234) < 1e-3
    assert result["source"] == "exif_gps"


def test_exif_jpeg_fixture_extracts_datetime():
    """EXIF DateTimeOriginal '2026:07:27 12:00:00' → UTC datetime."""
    from datetime import datetime, timezone
    data = JPEG_PATH.read_bytes()
    result = extract_gps_from_jpeg(data)
    assert result is not None
    assert result["datetime"] == datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)


def test_quicktime_mp4_fixture_extracts_kiev_coords():
    """MP4 with QuickTime ISO 6709 → (50.4501, 30.5234)."""
    data = MP4_PATH.read_bytes()
    result = extract_gps_from_quicktime(data)
    assert result is not None
    assert abs(result["lat"] - 50.4501) < 1e-3
    assert abs(result["lon"] - 30.5234) < 1e-3
    assert result["source"] == "quicktime_location"


def test_extract_gps_from_media_dispatches_jpeg():
    """extract_gps_from_media('image/jpeg') dispatches to extract_gps_from_jpeg."""
    data = JPEG_PATH.read_bytes()
    result = extract_gps_from_media(data, "image/jpeg")
    assert result is not None
    assert result["source"] == "exif_gps"


def test_extract_gps_from_media_dispatches_mp4():
    """extract_gps_from_media('video/mp4') dispatches to extract_gps_from_quicktime."""
    data = MP4_PATH.read_bytes()
    result = extract_gps_from_media(data, "video/mp4")
    assert result is not None
    assert result["source"] == "quicktime_location"